/*
 * SettingsView.java
 *
 * Created on Jan 16, 2012, 11:31:25 AM
 */
package view;

import controller.DoorController;
import controller.SettingsController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;

/**
 *
 * @author Jeff
 */
public class SettingsView extends javax.swing.JFrame {
    private DoorController forceDoor;
    private SettingsController settingsController;
    
    /** Creates new form SettingsView */
    public SettingsView() {
        forceDoor = new DoorController();
        initComponents();
        
    }

    public SettingsView(SettingsController settingsController) {

        this.settingsController = settingsController;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itopiaLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minutesSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        autoLogoutEnabledCheckbox = new javax.swing.JCheckBox();
        forceOpenDoorButton = new javax.swing.JButton();
        forceCloseDoorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instellingen");

        itopiaLogo.setFont(new java.awt.Font("Tahoma", 0, 36));
        itopiaLogo.setText("instellingen");
        itopiaLogo.setPreferredSize(new java.awt.Dimension(25, 64));

        jLabel1.setText("Log automatisch uit na");
        jLabel1.setToolTipText("Na x minuten niets gedaan te hebben zal de applicatie automatisch uitloggen en opnieuw om een admin-wachtwoord vragen");

        jLabel2.setText("minuten");

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        saveButton.setText("Opslaan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancelButton.setText("Annuleren");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        forceOpenDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_open.png"))); // NOI18N
        forceOpenDoorButton.setText("Deur Openen");
        forceOpenDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceOpenDoorButtonActionPerformed(evt);
            }
        });

        forceCloseDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        forceCloseDoorButton.setText("Deur Sluiten");
        forceCloseDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceCloseDoorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itopiaLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(forceCloseDoorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forceOpenDoorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(autoLogoutEnabledCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(10, 10, 10)
                        .addComponent(minutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap(186, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itopiaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(autoLogoutEnabledCheckbox))
                .addGap(10, 10, 10)
                .addComponent(forceOpenDoorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forceCloseDoorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            // Sla settings op in de database
            settingsController.saveSettings();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SettingsView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Do nothing and dispose
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

private void forceOpenDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forceOpenDoorButtonActionPerformed
    DoorController.doorController.openDoor();
}//GEN-LAST:event_forceOpenDoorButtonActionPerformed

private void forceCloseDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forceCloseDoorButtonActionPerformed
    DoorController.doorController.closeDoor();
}//GEN-LAST:event_forceCloseDoorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox autoLogoutEnabledCheckbox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton forceCloseDoorButton;
    private javax.swing.JButton forceOpenDoorButton;
    private javax.swing.JLabel itopiaLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JSpinner minutesSpinner;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
