
package view;

import controller.StatisticsController;
import java.util.ArrayList;
import model.LogEntry;
import model.User;
import model.Smartcard;


/**
 *
 * @author Vincent
 */
public class StatisticsView extends javax.swing.JFrame {
    private StatisticsController statisticsController;
    /** Creates new form StatisticsView */
    public StatisticsView() {
        initComponents();
    }

    /**
     * Initialiseert alle onderdelen in StatisticsView
     * 
     * @param statisticsController 
     */
    public StatisticsView(StatisticsController statisticsController) {
        this.statisticsController = statisticsController;
        initComponents();
        setGebruikersAantal();
        setLogAantal();
        setGebruikersBinnen();
        setBetredenVar();
        //setVerlatenVar();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        laatstVerlatenVar = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        laatstBetredenVar = new javax.swing.JTextPane();
        laatstVerlatenLabel = new javax.swing.JLabel();
        laatstBetredenLabel = new javax.swing.JLabel();
        gebruikersAantalLabel = new javax.swing.JLabel();
        logAantalLabel = new javax.swing.JLabel();
        gebruikersBinnenLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gebruikersBinnenVar = new javax.swing.JTextPane();
        gebruikersAantal = new outfitadminappmvc.FadeOnChangeLabelRunnable();
        logAantal = new outfitadminappmvc.FadeOnChangeLabelRunnable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistieken");

        laatstVerlatenVar.setEditable(false);
        laatstVerlatenVar.setFocusable(false);
        laatstVerlatenVar.setPreferredSize(new java.awt.Dimension(6, 6));
        jScrollPane2.setViewportView(laatstVerlatenVar);

        laatstBetredenVar.setEditable(false);
        laatstBetredenVar.setFocusable(false);
        laatstBetredenVar.setPreferredSize(new java.awt.Dimension(6, 6));
        jScrollPane1.setViewportView(laatstBetredenVar);

        laatstVerlatenLabel.setText("Laatst verlaten");

        laatstBetredenLabel.setText("Laatst betreden");

        gebruikersAantalLabel.setText("Gebruikers:");

        logAantalLabel.setText("Logitems:");

        gebruikersBinnenLabel.setText("Gebruikers die nu binnen zijn");

        gebruikersBinnenVar.setEditable(false);
        gebruikersBinnenVar.setFocusable(false);
        gebruikersBinnenVar.setPreferredSize(new java.awt.Dimension(6, 6));
        jScrollPane3.setViewportView(gebruikersBinnenVar);

        gebruikersAantal.setText("0");

        logAantal.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Statistieken");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gebruikersAantalLabel)
                                .addComponent(logAantalLabel))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logAantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gebruikersAantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(gebruikersBinnenLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(laatstBetredenLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(laatstVerlatenLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gebruikersAantalLabel)
                    .addComponent(gebruikersAantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logAantalLabel)
                    .addComponent(logAantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laatstBetredenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laatstVerlatenLabel)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gebruikersBinnenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * setGebuikersAantal telt hoeveel gebruikers er in de arraylist users zit
     */
    public static void setGebruikersAantal(){
        gebruikersAantal.setText(Integer.toString(User.users.size()));
        //gebruikersAantal.setText("2323");
    }
    /**
     * setLogAantal telt hoeveel logEntries er in de arraylist logEntriers zit
     */
    public static void setLogAantal(){
        logAantal.setText(Integer.toString(LogEntry.logEntries.size()));
    }

    /**
     * setBetredenVar vult LaatsBetredenVar met de laatste 5 gebruikers die het gebouw betreden hebben
     */
    public static void setBetredenVar(){
        String LaatsBetredenString = "";
        for(User user : LogEntry.usersBeenInside){
            LaatsBetredenString = LaatsBetredenString + user.getVoornaam() + " " + user.getAchternaam() + "\n";
        }
        laatstBetredenVar.setText(LaatsBetredenString);
    }
    /**
     * setVerlatenVar vult LaatsVerlatenVar met de laatste 5 gebruikers die het gebouw verlaten hebben
     */
    public static void setVerlatenVar(){
        String laatstVerlatenString = "";
        ArrayList<LogEntry> arrayList = LogEntry.logEntries;
        int i = 0;
        for(LogEntry arr: arrayList)
        {
           if(arr.getLog_types_id() == 5)
           {
                   laatstVerlatenString = laatstVerlatenString + arr.getUser().getVoornaam() + "\n";
          
           }
            
            
        }
        laatstVerlatenVar.setText(laatstVerlatenString);
    }
    /**
     * setGebruikersBinnen vult gebruikersBinnenVar met de gebruikers die op dit moment in het bebouw zijn
     */
    public static void setGebruikersBinnen(){
        String gebruikersBinnenString = "";
        
        
        if(!LogEntry.usersInside.isEmpty())
        {
        for(User user : LogEntry.usersInside)
        {
            gebruikersBinnenString += gebruikersBinnenString + user.getVoornaam() + " " + user.getAchternaam() + "\n";
            
        }
        }
        
        
        gebruikersBinnenVar.setText(gebruikersBinnenString);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static outfitadminappmvc.FadeOnChangeLabelRunnable gebruikersAantal;
    private javax.swing.JLabel gebruikersAantalLabel;
    private javax.swing.JLabel gebruikersBinnenLabel;
    private static javax.swing.JTextPane gebruikersBinnenVar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel laatstBetredenLabel;
    private static javax.swing.JTextPane laatstBetredenVar;
    private javax.swing.JLabel laatstVerlatenLabel;
    private static javax.swing.JTextPane laatstVerlatenVar;
    private static outfitadminappmvc.FadeOnChangeLabelRunnable logAantal;
    private javax.swing.JLabel logAantalLabel;
    // End of variables declaration//GEN-END:variables
}
