/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersView.java
 *
 * Created on Dec 29, 2011, 1:16:47 AM
 */
package view;

import controller.UsersController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author Mauricio
 */
public class UsersView extends javax.swing.JFrame {
    private UsersController usersController;
    private DefaultTableModel tm;

    /** 
     * Creates new form UsersView 
     */
	public UsersView() {
		initComponents();
	}
        /**
         * Maakt nieuwe JFrame van Users en haalt de gebruikers op
         * @param usersController controller
         */
	public UsersView(UsersController usersController) {
		this.usersController = usersController;
		initComponents();
		processUsers();
	}
    /**
     * Haalt gebruikers op en zet deze in de JTable, disabled ook de editable cells 
     */
    public void processUsers() {
        ArrayList<User> arrayList = User.users;

        if (!arrayList.isEmpty()) {

            tm = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };

            tm.addColumn("Voornaam");
            tm.addColumn("Achternaam");
            tm.addColumn("Tag");
            tm.addColumn("UID");


            for (User arr : arrayList) {
                //usersdump.append(
                //	arr.getVoornaam() + " " + arr.getAchternaam() + " " +
                //	arr.getTag() + "\n"
                //);

                tm.addRow(new String[]{arr.getVoornaam(), arr.getAchternaam(), arr.getTag(), arr.getId() + ""});
            }
            usersTable.setModel(tm);
        } else {
            //usersdump.setText(noUsersMsg);
        }
    }
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kopLabel = new javax.swing.JLabel();
        showUserView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        removeUser = new javax.swing.JButton();
        editUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gebruikerslijst");

        kopLabel.setText("Gebruikerslijst");

        showUserView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        showUserView.setToolTipText("Gebruiker toevoegen");
        showUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserViewActionPerformed(evt);
            }
        });

        usersTable.setAutoCreateRowSorter(true);
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Laden..."}
            },
            new String [] {
                "Gebruiker"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setRowSorter(null);
        usersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(usersTable);

        removeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        removeUser.setToolTipText("Gebruiker verwijderen");
        removeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserActionPerformed(evt);
            }
        });

        editUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        editUser.setToolTipText("Gebruiker bewerken");
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(kopLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 222, Short.MAX_VALUE)
                        .add(editUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(removeUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(showUserView, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(kopLabel)
                        .add(showUserView))
                    .add(removeUser)
                    .add(editUser))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
         * Laadt UserView via controller
         * @param evt 
         */
	private void showUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserViewActionPerformed
		// TODO add your handling code here:
		usersController.showUserView();
	}//GEN-LAST:event_showUserViewActionPerformed
        /**
         * Verwijderd een gebruiker uit de tabel + database via controller 
         * @param evt 
         */
private void removeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserActionPerformed
// TODO add your handling code here:
    usersController.removeUser(usersTable, tm);
}//GEN-LAST:event_removeUserActionPerformed
/**
 * Bewerken van de gebruikersgegevens via ingevulde UserView (via controller)
 * @param evt 
 */
private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
// TODO add your handling code here:
    usersController.editUser(usersTable, tm);
    
}//GEN-LAST:event_editUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editUser;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel kopLabel;
    private javax.swing.JButton removeUser;
    private javax.swing.JButton showUserView;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

}
