/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginView.java
 *
 * Created on Dec 21, 2011, 8:17:20 PM
 */
package view;

import controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Razzy
 */
public class LoginView extends javax.swing.JFrame {
    private LoginController loginController;
    
    
    /** Creates new form LoginView */
    public LoginView() {
        initComponents();
    }

    public LoginView(LoginController logincontroller) {

        this.loginController = logincontroller;
        initComponents();
        
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public void setPasswordField(JPasswordField passwordField) {
        this.passwordField = passwordField;
    }
    
    /**
     * Deze methode reset het passwordveld
     */
    public void resetPasswordField() {
        passwordField.setText("");
    }

    public String getFirstname() {
        return firstnameTextField.getText();
    }
    public String getLastname() {
        return lastnameTextField.getText();
    }

    public void setUsernameTextField(JTextField usernameTextField) {
        // waarom krijg ik dit niet weg? >_<
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        itopiaLogo = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        lastnameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        firstnameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));

        northPanel.setMinimumSize(new java.awt.Dimension(400, 75));
        northPanel.setPreferredSize(new java.awt.Dimension(400, 75));
        northPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itopiaLogo.setFont(new java.awt.Font("Tahoma", 0, 36));
        itopiaLogo.setText("login");
        itopiaLogo.setPreferredSize(new java.awt.Dimension(25, 64));
        northPanel.add(itopiaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, -1));

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        southPanel.setMinimumSize(new java.awt.Dimension(400, 200));
        southPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        southPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                southPanelKeyReleased(evt);
            }
        });
        southPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        lastnameLabel.setText("Achternaam:");
        southPanel.add(lastnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        passwordLabel.setText("Wachtwoord:");
        southPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lastnameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextFieldActionPerformed(evt);
            }
        });
        southPanel.add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        southPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_in.png"))); // NOI18N
        loginButton.setText("Log in    ");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        southPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));

        errorLabel.setFont(new java.awt.Font("Calibri", 2, 14));
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exclamation.png"))); // NOI18N
        errorLabel.setText("Niet-bestaande gebruikersnaam of wachtwoord  ");
        southPanel.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        firstnameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        southPanel.add(firstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, -1));

        firstnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        firstnameLabel.setText("Voornaam: ");
        southPanel.add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(southPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        try {
            loginController.checkLoginData();
        } catch (SQLException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonMousePressed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        if(evt.getKeyCode() == 10) {
            try {
                loginController.checkLoginData();
            } catch (SQLException ex) {
                Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void southPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_southPanelKeyReleased

    }//GEN-LAST:event_southPanelKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel errorLabel;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel itopiaLogo;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
