/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Dec 15, 2011, 1:38:38 PM
 */
package view;

import controller.LogController;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Razzy
 */
public class LogView extends javax.swing.JFrame {


    private class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
            setForeground(table.getSelectionForeground());
            setBackground(table.getSelectionBackground());
        } else {
            setForeground(table.getForeground());
            setBackground(UIManager.getColor("Button.background"));
        }
        setText((value == null) ? "" : value.toString());
        return this;
        }
    }
	private LogController logController;

    /** Creates new form GUI */
    public LogView() {
        initComponents();
    }

	public LogView(LogController logController) {
		this.logController = logController;
		initComponents();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanell = new javax.swing.JPanel();
        todayButton = new javax.swing.JButton();
        hackattemptsButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        allesButton = new javax.swing.JButton();
        logoffButton = new javax.swing.JButton();
        southPanel = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminApp");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 590));

        northPanell.setBackground(new java.awt.Color(255, 255, 255));
        northPanell.setMinimumSize(new java.awt.Dimension(0, 50));
        northPanell.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                northPanellComponentMoved(evt);
            }
        });

        todayButton.setText("Vandaag");
        todayButton.setAlignmentX(30);
        todayButton.setMaximumSize(new java.awt.Dimension(110, 55));
        todayButton.setMinimumSize(new java.awt.Dimension(110, 55));
        todayButton.setPreferredSize(new java.awt.Dimension(110, 55));
        todayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayButtonActionPerformed(evt);
            }
        });

        hackattemptsButton.setText("Hack Attempts");
        hackattemptsButton.setPreferredSize(new java.awt.Dimension(110, 50));
        hackattemptsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hackattemptsButtonActionPerformed(evt);
            }
        });

        statisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        statisticsButton.setToolTipText("Statistieken");
        statisticsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        statisticsButton.setMaximumSize(new java.awt.Dimension(32, 32));
        statisticsButton.setMinimumSize(new java.awt.Dimension(32, 32));
        statisticsButton.setPreferredSize(new java.awt.Dimension(32, 32));
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naam", "Locatie", "Bijzonderheden", "Tijd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        jScrollPane1.setViewportView(logTable);

        allesButton.setText("Alles");
        allesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allesButtonActionPerformed(evt);
            }
        });

        logoffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        logoffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout northPanellLayout = new javax.swing.GroupLayout(northPanell);
        northPanell.setLayout(northPanellLayout);
        northPanellLayout.setHorizontalGroup(
            northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(northPanellLayout.createSequentialGroup()
                        .addComponent(todayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hackattemptsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(statisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        northPanellLayout.setVerticalGroup(
            northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(allesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(todayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hackattemptsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(northPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(logoffButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statisticsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        );

        getContentPane().add(northPanell, java.awt.BorderLayout.NORTH);

        southPanel.setBackground(new java.awt.Color(255, 255, 255));
        southPanel.setMinimumSize(new java.awt.Dimension(0, 50));

        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        userButton.setText("Gebruikers");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrench_orange.png"))); // NOI18N
        settingsButton.setText("Instellingen");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        exportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk_multiple.png"))); // NOI18N
        exportButton.setText("Exporteer");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userButton)
                    .addComponent(settingsButton)
                    .addComponent(exportButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(southPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayButtonActionPerformed
        logController.refreshTable("today");
   
    }//GEN-LAST:event_todayButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
                logController.showStatistics();
    }//GEN-LAST:event_statisticsButtonActionPerformed

    private void hackattemptsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hackattemptsButtonActionPerformed
        logController.refreshTable("hack");
          
    }//GEN-LAST:event_hackattemptsButtonActionPerformed

    private void northPanellComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_northPanellComponentMoved
        
    }//GEN-LAST:event_northPanellComponentMoved

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        logController.showUsers();
    }
    
        // TODO add your handling code here:         logController.showUsers();     }//GEN-LAST:event_userButtonActionPerformed

    private void allesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allesButtonActionPerformed
        
        logController.refreshTable(""); // lege string is "alles"-filter
        
        // Temporary test (Jeff)
        // dit werkt
        
        
        //tm.setDataVector(new Object[][] {{"Rij een cel een", "Rij een cel twee"}, {"Rij twee cel een", "Rij twee cel twee"}}, new Object[] {"Colnaam1", "Colnaam2"});
        
        //logTable.getColumn("Colnaam1").setCellRenderer(new ButtonRenderer());
        //logTable.getColumn("Colnaam1").setCellEditor(new ButtonEditor(new JCheckBox()));
    }//GEN-LAST:event_allesButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        logController.showSettings();
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        logController.exportLog();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void logoffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffButtonActionPerformed
        logController.logOff();
    }//GEN-LAST:event_logoffButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allesButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton hackattemptsButton;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable logTable;
    private javax.swing.JButton logoffButton;
    private javax.swing.JPanel northPanell;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel southPanel;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JButton todayButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
